export const restaurantList = [
  {
    storeId: "store_001",
    storeLogo: "https://placehold.co/100x100",
    storeName: "맛있는 치킨",
    rating: 4.8,
    reviewCount: 128,
    baseDeliveryTip: 3000,
    minDeliveryTime: "25",
    maxDeliveryTime: "40",
    discountPrice: 2000,
    status: "OPEN",
  },
  {
    storeId: "store_002",
    storeLogo: "https://placehold.co/100x100",
    storeName: "피자나라",
    rating: 4.5,
    reviewCount: 256,
    baseDeliveryTip: 2500,
    minDeliveryTime: "30",
    maxDeliveryTime: "45",
    discountPrice: 3000,
    status: "OPEN",
  },
  {
    storeId: "store_003",
    storeLogo: "https://placehold.co/100x100",
    storeName: "중국관",
    rating: 4.2,
    reviewCount: 89,
    baseDeliveryTip: 2000,
    minDeliveryTime: "20",
    maxDeliveryTime: "35",
    discountPrice: 1500,
    status: "OPEN",
  },
  {
    storeId: "store_004",
    storeLogo: "https://placehold.co/100x100",
    storeName: "돈까스 하우스",
    rating: 4.7,
    reviewCount: 167,
    baseDeliveryTip: 3500,
    minDeliveryTime: "35",
    maxDeliveryTime: "50",
    discountPrice: 2500,
    status: "CLOSED",
  },
  {
    storeId: "store_005",
    storeLogo: "https://placehold.co/100x100",
    storeName: "분식이야기",
    rating: 4.4,
    reviewCount: 142,
    baseDeliveryTip: 2000,
    minDeliveryTime: "15",
    maxDeliveryTime: "30",
    discountPrice: 1000,
    status: "OPEN",
  },
  {
    storeId: "store_006",
    storeLogo: "https://placehold.co/100x100",
    storeName: "한식대첩",
    rating: 4.6,
    reviewCount: 198,
    baseDeliveryTip: 2800,
    minDeliveryTime: "25",
    maxDeliveryTime: "40",
    discountPrice: 2000,
    status: "OPEN",
  },
  {
    storeId: "store_007",
    storeLogo: "https://placehold.co/100x100",
    storeName: "일식천국",
    rating: 4.9,
    reviewCount: 221,
    baseDeliveryTip: 4000,
    minDeliveryTime: "40",
    maxDeliveryTime: "55",
    discountPrice: 3500,
    status: "CLOSED",
  },
  {
    storeId: "store_008",
    storeLogo: "https://placehold.co/100x100",
    storeName: "버거킹덤",
    rating: 4.3,
    reviewCount: 156,
    baseDeliveryTip: 3000,
    minDeliveryTime: "30",
    maxDeliveryTime: "45",
    discountPrice: 2500,
    status: "OPEN",
  },
  {
    storeId: "store_009",
    storeLogo: "https://placehold.co/100x100",
    storeName: "샐러드팜",
    rating: 4.5,
    reviewCount: 92,
    baseDeliveryTip: 2500,
    minDeliveryTime: "20",
    maxDeliveryTime: "35",
    discountPrice: 1500,
    status: "OPEN",
  },
  {
    storeId: "store_010",
    storeLogo: "https://placehold.co/100x100",
    storeName: "파스타월드",
    rating: 4.7,
    reviewCount: 178,
    baseDeliveryTip: 3500,
    minDeliveryTime: "35",
    maxDeliveryTime: "50",
    discountPrice: 3000,
    status: "CLOSED",
  },
]
