import { StoreStatus, UsersStoreDetailResponseDto } from "@/types/Store"

export const detailedStoreData: UsersStoreDetailResponseDto[] = [
  {
    storeId: "store_001",
    storeName: "맛있는 치킨",
    rating: 4.8,
    reviewCount: 128,
    defaultDeliveryTip: 3000,
    minDeliveryTime: "25",
    maxDeliveryTime: "40",
    storeImage: "https://placehold.co/400x224",
    minimumOrderPrice: 16000,
    ownerCouponId: 1001,
    storeStatus: StoreStatus.OPEN,
    usersMenuGroup: [
      {
        groupId: 1,
        groupName: "인기메뉴",
        menus: [
          {
            menuId: "1001",
            menuName: "황금올리브치킨",
            price: 18000,
            menuContent: "바삭하고 고소한 올리브유 치킨",
            menuImage: "https://placehold.co/100x100",
            menuOption: 1,
            isSoldOut: false,
          },
          {
            menuId: "1002",
            menuName: "허니갈릭치킨",
            price: 19000,
            menuContent: "달콤한 꿀과 갈릭의 완벽한 조화",
            menuImage: "https://placehold.co/100x100",
            menuOption: 1,
            isSoldOut: false,
          },
        ],
      },
      {
        groupId: 2,
        groupName: "사이드메뉴",
        menus: [
          {
            menuId: "1003",
            menuName: "치즈볼",
            price: 5000,
            menuContent: "모짜렐라 치즈가 가득한 치즈볼",
            menuImage: "https://placehold.co/100x100",
            menuOption: 0,
            isSoldOut: false,
          },
        ],
      },
    ],
    usersMenus: [
      {
        menuId: "1001",
        menuName: "황금올리브치킨",
        price: 18000,
        menuContent: "바삭하고 고소한 올리브유 치킨",
        menuImage: "https://placehold.co/100x100",
        menuOption: 1,
        isSoldOut: false,
      },
      {
        menuId: "1002",
        menuName: "허니갈릭치킨",
        price: 19000,
        menuContent: "달콤한 꿀과 갈릭의 완벽한 조화",
        menuImage: "https://placehold.co/100x100",
        menuOption: 1,
        isSoldOut: false,
      },
      {
        menuId: "1003",
        menuName: "치즈볼",
        price: 5000,
        menuContent: "모짜렐라 치즈가 가득한 치즈볼",
        menuImage: "https://placehold.co/100x100",
        menuOption: 0,
        isSoldOut: false,
      },
    ],
  },
  {
    storeId: "store_002",
    storeName: "피자나라",
    rating: 4.5,
    reviewCount: 256,
    defaultDeliveryTip: 2500,
    minDeliveryTime: "30",
    maxDeliveryTime: "45",
    storeImage: "https://placehold.co/400x224",
    minimumOrderPrice: 15000,
    ownerCouponId: 1002,
    storeStatus: StoreStatus.OPEN,
    usersMenuGroup: [
      {
        groupId: 1,
        groupName: "프리미엄 피자",
        menus: [
          {
            menuId: "2001",
            menuName: "슈퍼슈프림",
            price: 25000,
            menuContent: "풍성한 토핑이 가득한 피자의 왕",
            menuImage: "https://placehold.co/100x100",
            menuOption: 1,
            isSoldOut: false,
          },
          {
            menuId: "2002",
            menuName: "불고기피자",
            price: 23000,
            menuContent: "한국인의 입맛에 딱 맞는 불고기피자",
            menuImage: "https://placehold.co/100x100",
            menuOption: 1,
            isSoldOut: false,
          },
        ],
      },
      {
        groupId: 2,
        groupName: "사이드메뉴",
        menus: [
          {
            menuId: "2003",
            menuName: "파스타",
            price: 8000,
            menuContent: "알덴테로 삶은 크림파스타",
            menuImage: "https://placehold.co/100x100",
            menuOption: 0,
            isSoldOut: false,
          },
        ],
      },
    ],
    usersMenus: [
      {
        menuId: "2001",
        menuName: "슈퍼슈프림",
        price: 25000,
        menuContent: "풍성한 토핑이 가득한 피자의 왕",
        menuImage: "https://placehold.co/100x100",
        menuOption: 1,
        isSoldOut: false,
      },
      {
        menuId: "2002",
        menuName: "불고기피자",
        price: 23000,
        menuContent: "한국인의 입맛에 딱 맞는 불고기피자",
        menuImage: "https://placehold.co/100x100",
        menuOption: 1,
        isSoldOut: false,
      },
      {
        menuId: "2003",
        menuName: "파스타",
        price: 8000,
        menuContent: "알덴테로 삶은 크림파스타",
        menuImage: "https://placehold.co/100x100",
        menuOption: 0,
        isSoldOut: false,
      },
    ],
  },
]
