import { NextResponse } from "next/server";

const mockCoupons = [
  {
    couponId: 1,
    couponName: "Black Friday Discount",
    couponType: "FirstCome",
    discountPrice: 5000,
    discountType: "FIXED",
    minOrderPrice: 20000,
    maximumDiscount: 10000,
    maxIssuance: 100,
    expiredDate: "2024-12-31T23:59:59",
    downloadStartDate: "2024-11-30T00:00:00",
    couponStatus: "ACTIVE",
    couponDescription: "선착순 100명 대상 특별 할인",
  },
  {
    couponId: 2,
    couponName: "Welcome Discount",
    couponType: "Regular",
    discountPrice: 10000,
    discountType: "FIXED",
    minOrderPrice: 50000,
    maximumDiscount: null,
    maxIssuance: null,
    expiredDate: "2025-01-01T23:59:59",
    downloadStartDate: null,
    couponStatus: "PENDING",
    couponDescription: "새로운 고객을 위한 특별 할인",
  },
  {
    couponId: 3,
    couponName: "Holiday Special",
    couponType: "Limited",
    discountPrice: 15,
    discountType: "PERCENTAGE",
    minOrderPrice: 30000,
    maximumDiscount: 10000,
    maxIssuance: 50,
    expiredDate: "2024-12-25T23:59:59",
    downloadStartDate: "2024-12-01T00:00:00",
    couponStatus: "ACTIVE",
    couponDescription: "크리스마스 시즌 한정 할인",
  },
  {
    couponId: 4,
    couponName: "Free Shipping",
    couponType: "Freebie",
    discountPrice: 0,
    discountType: "FIXED",
    minOrderPrice: 30000,
    maximumDiscount: null,
    maxIssuance: 1000,
    expiredDate: "2024-12-31T23:59:59",
    downloadStartDate: null,
    couponStatus: "ACTIVE",
    couponDescription: "3만 원 이상 구매 시 무료 배송",
  },
  {
    couponId: 5,
    couponName: "VIP Exclusive",
    couponType: "Regular",
    discountPrice: 20000,
    discountType: "FIXED",
    minOrderPrice: 80000,
    maximumDiscount: null,
    maxIssuance: null,
    expiredDate: "2024-12-31T23:59:59",
    downloadStartDate: "2024-11-15T00:00:00",
    couponStatus: "EXPIRED",
    couponDescription: "VIP 고객만 사용할 수 있는 특별 할인",
  },
  {
    couponId: 6,
    couponName: "Summer Sale",
    couponType: "Seasonal",
    discountPrice: 10,
    discountType: "PERCENTAGE",
    minOrderPrice: 20000,
    maximumDiscount: 5000,
    maxIssuance: 300,
    expiredDate: "2024-08-31T23:59:59",
    downloadStartDate: "2024-07-01T00:00:00",
    couponStatus: "EXPIRED",
    couponDescription: "여름 시즌 한정 할인 이벤트",
  },
  {
    couponId: 7,
    couponName: "Referral Bonus",
    couponType: "Regular",
    discountPrice: 5000,
    discountType: "FIXED",
    minOrderPrice: 20000,
    maximumDiscount: null,
    maxIssuance: null,
    expiredDate: "2025-01-31T23:59:59",
    downloadStartDate: null,
    couponStatus: "ACTIVE",
    couponDescription: "친구 추천으로 받을 수 있는 할인",
  },
  {
    couponId: 8,
    couponName: "Flash Sale",
    couponType: "FirstCome",
    discountPrice: 7000,
    discountType: "FIXED",
    minOrderPrice: 30000,
    maximumDiscount: null,
    maxIssuance: 100,
    expiredDate: "2024-12-10T23:59:59",
    downloadStartDate: "2024-12-05T00:00:00",
    couponStatus: "ACTIVE",
    couponDescription: "선착순 100명 대상 번개 세일 할인",
  },
  {
    couponId: 9,
    couponName: "New Year Discount",
    couponType: "Seasonal",
    discountPrice: 5000,
    discountType: "FIXED",
    minOrderPrice: 15000,
    maximumDiscount: null,
    maxIssuance: 500,
    expiredDate: "2025-01-10T23:59:59",
    downloadStartDate: "2025-01-01T00:00:00",
    couponStatus: "PENDING",
    couponDescription: "새해를 맞이하여 제공되는 특별 할인",
  },
  {
    couponId: 10,
    couponName: "Loyalty Reward",
    couponType: "Regular",
    discountPrice: 2000,
    discountType: "FIXED",
    minOrderPrice: 10000,
    maximumDiscount: null,
    maxIssuance: null,
    expiredDate: "2025-06-30T23:59:59",
    downloadStartDate: null,
    couponStatus: "ACTIVE",
    couponDescription: "충성 고객에게 드리는 감사 쿠폰",
  },
];

export async function GET() {
  return NextResponse.json(mockCoupons);
}
